-- Default Admin User (password is 'admin' encoded with NoOp password encoder)
MERGE INTO TOOL_APP_USER KEY(username) VALUES (1, 'admin', '{noop}admin', 'ROLE_ADMIN');

-- Insert initial config
MERGE INTO TOOL_PATCH_CONFIG KEY(id) VALUES (1, 
    0, 0, 0, '$FIXEDLENGTHSTRING$_$3DIGITSEQUENCE$_$YYYMMDD$', '$LASTDEPLOYEDPATCH$_DF_$3DIGITSEQUENCE$_$YYYMMDD$', 'NONE', 
    0, 0, 0, '$FIXEDLENGTHSTRING$_$3DIGITSEQUENCE$_$YYYMMDD$', '$LASTDEPLOYEDPATCH$_DF_$3DIGITSEQUENCE$_$YYYMMDD$', 'NONE', 
    0, 0, 0, '$FIXEDLENGTHSTRING$_$3DIGITSEQUENCE$_$YYYMMDD$', '$LASTDEPLOYEDPATCH$_DF_$3DIGITSEQUENCE$_$YYYMMDD$', 'NONE'
);
